CREATE TABLE Soldado (
	Identificador INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	Nombre VARCHAR(50)
);

CREATE TABLE Arma (
	Identificador INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	Danyo SMALLINT UNSIGNED,
	Peso TINYINT UNSIGNED,
	Cargador SMALLINT UNSIGNED,
	Cadencia TINYINT UNSIGNED,
	Modificadores VARCHAR(200)
);

CREATE TABLE Armamento (
	Identificador INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ReferenciaSoldado INT UNSIGNED,
	FOREIGN KEY (ReferenciaSoldado) REFERENCES Soldado (Identificador) ON DELETE CASCADE,
	ReferenciaArma INT UNSIGNED,
	FOREIGN KEY (ReferenciaArma) REFERENCES Arma (Identificador) ON DELETE CASCADE
);
	